include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

# https://dart.dev/tools/linter-rules
linter:
  rules:
    prefer_relative_imports: true
    avoid_print: true
    prefer_single_quotes: false
    sort_constructors_first: true
    sort_child_properties_last: true
    always_declare_return_types: true

analyzer:
  exclude:
    - "build/**"
    - "lib/**.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true