name: neurothrone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Core Flutter Packages
  collection: ^1.19.1

  # UI and Design
  google_fonts: ^6.3.0

  # Navigation
  go_router: ^16.1.0

  # Dependency Injection
  get_it: ^8.2.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage
  shared_preferences: ^2.5.3

  # Networking
  dio: ^5.9.0

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # Date and Time
  intl: ^0.20.2

  # JSON Serialization
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

  package_info_plus: ^8.3.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  json_serializable: ^6.10.0
  freezed: ^3.2.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/data/projects.json

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode.ttf