name: neurothrone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Navigation
  go_router: ^16.0.0

  # Dependency Injection
  get_it: ^8.0.3

  # State Management
  flutter_riverpod: ^2.6.1

  flutter_dotenv: ^5.2.1

  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env